version: "3.8"

services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_app}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - SERVICES=apigateway,cloudformation,cloudwatch,dynamodb,ec2,es,firehose,iam,kinesis,kms,lambda,route53,rds,redshift,s3,secretmanager,ses,sns,sqs,ssm,stepfunctions,sts,elasticache
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstackKeyId
      - AWS_SECRET_ACCESS_KEY=Tulipa89!
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-./.docker/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"