version: "3.8"
services:

  postgres_db:
    container_name: postgres_db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=Salmos89!
      - POSTGRES_USER=adm_address
      - POSTGRES_DB=adm_address_db
    volumes:
      - './.docker/db/data:/var/lib/postgresql/data'
    networks:
      - db-net

networks:
  db-net:
    driver: bridge